services:
    # Event Listeners
    mautic.lodge.subscriber.token:
        class: MauticPlugin\LodgeSubscriptionPlugin\EventListener\TokenSubscriber
        arguments:
            - '@mautic.lodge.service.stripe'
        tags:
            - { name: kernel.event_subscriber }
            
    mautic.lodge.subscriber.builder:
        class: MauticPlugin\LodgeSubscriptionPlugin\EventListener\BuilderSubscriber
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    # Forms
    mautic.lodge.form.type.config:
        class: MauticPlugin\LodgeSubscriptionPlugin\Form\Type\ConfigType
        arguments: []
        tags:
            - { name: form.type }

    # Models
    mautic.lodge.model.subscription:
        class: MauticPlugin\LodgeSubscriptionPlugin\Model\SubscriptionModel
        arguments:
            - '@doctrine.orm.entity_manager'

    # Services
    mautic.lodge.service.stripe:
        class: MauticPlugin\LodgeSubscriptionPlugin\Services\StripeService
        arguments:
            - '@mautic.helper.integration'
            - '@router'
            - '@mautic.lodge.helper.subscription'

    mautic.lodge.helper.subscription:
        class: MauticPlugin\LodgeSubscriptionPlugin\Helper\SubscriptionHelper
        arguments:
            - '@mautic.lead.model.lead'
            - '@doctrine.orm.entity_manager'
            - '@mautic.user.model.user'

    # Integration
    mautic.integration.lodge:
        class: MauticPlugin\LodgeSubscriptionPlugin\Integration\LodgeSubscriptionIntegration
        arguments:
            - '@event_dispatcher'
            - '@mautic.helper.cache_storage'
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@request_stack'
            - '@router'
            - '@translator'
            - '@logger'
            - '@mautic.helper.encryption'
            - '@mautic.lead.model.lead'
            - '@mautic.lead.model.company'
            - '@mautic.helper.paths'
            - '@mautic.core.model.notification'
            - '@mautic.lead.model.field'
            - '@mautic.plugin.model.integration_entity'
            - '@mautic.lead.model.dnc'
        tags:
            - { name: mautic.integration, isPlugin: true }

    # Commands
    mautic.lodge.command.yearend:
        class: MauticPlugin\LodgeSubscriptionPlugin\Command\YearEndProcessCommand
        arguments:
            - '@mautic.lodge.helper.subscription'
            - '@mautic.lead.model.field'
            - '@mautic.email.model.email'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: console.command } 